//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrefourPolaire.Resources.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CarrefourPolaire.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string LogoAlt {
            get {
                return ResourceManager.GetString("LogoAlt", resourceCulture);
            }
        }
        
        internal static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        internal static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        internal static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        internal static string MenuButton {
            get {
                return ResourceManager.GetString("MenuButton", resourceCulture);
            }
        }
        
        internal static string WhenTitle {
            get {
                return ResourceManager.GetString("WhenTitle", resourceCulture);
            }
        }
        
        internal static string WhenValue {
            get {
                return ResourceManager.GetString("WhenValue", resourceCulture);
            }
        }
        
        internal static string WhereTitle {
            get {
                return ResourceManager.GetString("WhereTitle", resourceCulture);
            }
        }
        
        internal static string WhereValue {
            get {
                return ResourceManager.GetString("WhereValue", resourceCulture);
            }
        }
        
        internal static string WhoTitle {
            get {
                return ResourceManager.GetString("WhoTitle", resourceCulture);
            }
        }
        
        internal static string WhoValue {
            get {
                return ResourceManager.GetString("WhoValue", resourceCulture);
            }
        }
        
        internal static string WhatToExpectTitle {
            get {
                return ResourceManager.GetString("WhatToExpectTitle", resourceCulture);
            }
        }
        
        internal static string Feature1Title {
            get {
                return ResourceManager.GetString("Feature1Title", resourceCulture);
            }
        }
        
        internal static string Feature1Text {
            get {
                return ResourceManager.GetString("Feature1Text", resourceCulture);
            }
        }
        
        internal static string Feature2Title {
            get {
                return ResourceManager.GetString("Feature2Title", resourceCulture);
            }
        }
        
        internal static string Feature2Text {
            get {
                return ResourceManager.GetString("Feature2Text", resourceCulture);
            }
        }
        
        internal static string Feature3Title {
            get {
                return ResourceManager.GetString("Feature3Title", resourceCulture);
            }
        }
        
        internal static string Feature3Text {
            get {
                return ResourceManager.GetString("Feature3Text", resourceCulture);
            }
        }
        
        internal static string WhatToExpect_ServiceActivity_Title {
            get {
                return ResourceManager.GetString("WhatToExpect.ServiceActivity.Title", resourceCulture);
            }
        }
        
        internal static string WhatToExpect_ServiceActivity_Description {
            get {
                return ResourceManager.GetString("WhatToExpect.ServiceActivity.Description", resourceCulture);
            }
        }
    }
}
