//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarrefourPolaire.Resources.Pages.About {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CarrefourPolaire.Resources.Pages.About.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string WhatIsTitle {
            get {
                return ResourceManager.GetString("WhatIsTitle", resourceCulture);
            }
        }
        
        internal static string IntroPart1 {
            get {
                return ResourceManager.GetString("IntroPart1", resourceCulture);
            }
        }
        
        internal static string IntroStrongPart {
            get {
                return ResourceManager.GetString("IntroStrongPart", resourceCulture);
            }
        }
        
        internal static string IntroPart2 {
            get {
                return ResourceManager.GetString("IntroPart2", resourceCulture);
            }
        }
        
        internal static string IntroEmphasisPart {
            get {
                return ResourceManager.GetString("IntroEmphasisPart", resourceCulture);
            }
        }
        
        internal static string IntroPart3 {
            get {
                return ResourceManager.GetString("IntroPart3", resourceCulture);
            }
        }
        
        internal static string ProvincialTitle {
            get {
                return ResourceManager.GetString("ProvincialTitle", resourceCulture);
            }
        }
        
        internal static string ProvincialDescription {
            get {
                return ResourceManager.GetString("ProvincialDescription", resourceCulture);
            }
        }
        
        internal static string WhyCarrefourTitle {
            get {
                return ResourceManager.GetString("WhyCarrefourTitle", resourceCulture);
            }
        }
        
        internal static string WhyCarrefourPart1 {
            get {
                return ResourceManager.GetString("WhyCarrefourPart1", resourceCulture);
            }
        }
        
        internal static string WhyCarrefourEmphasis {
            get {
                return ResourceManager.GetString("WhyCarrefourEmphasis", resourceCulture);
            }
        }
        
        internal static string WhyCarrefourPart2 {
            get {
                return ResourceManager.GetString("WhyCarrefourPart2", resourceCulture);
            }
        }
        
        internal static string ActivitiesTitle {
            get {
                return ResourceManager.GetString("ActivitiesTitle", resourceCulture);
            }
        }
        
        internal static string Activity1 {
            get {
                return ResourceManager.GetString("Activity1", resourceCulture);
            }
        }
        
        internal static string Activity2 {
            get {
                return ResourceManager.GetString("Activity2", resourceCulture);
            }
        }
        
        internal static string Activity3 {
            get {
                return ResourceManager.GetString("Activity3", resourceCulture);
            }
        }
        
        internal static string Activity4 {
            get {
                return ResourceManager.GetString("Activity4", resourceCulture);
            }
        }
        
        internal static string Activity5 {
            get {
                return ResourceManager.GetString("Activity5", resourceCulture);
            }
        }
        
        internal static string ExperienceTitle {
            get {
                return ResourceManager.GetString("ExperienceTitle", resourceCulture);
            }
        }
        
        internal static string ExperienceDescription {
            get {
                return ResourceManager.GetString("ExperienceDescription", resourceCulture);
            }
        }
        
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        internal static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
    }
}
